Repository AY2223S2-CS2103T-T15-3/tp, pull requests merged in 2023-03, with the labels that each got.

#2 Implement initial basic Homepage UI layout
  docs/images/bipbipboopboop.png
  src/main/java/seedu/address/Main.java
  src/main/java/seedu/address/MainUi.java
Labels: enhancement, gui

#4 Update personal information of VietAnh1010
  docs/AboutUs.md
  docs/images/vietanh1010.png
  docs/team/vietanh1010.md
Labels: documentation

#6 Implement remark command
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
Labels: enhancement, cli

#52 Connect UI with backend
  src/main/java/vimification/MainApp
  src/main/java/vimification/MainUi.java
  src/main/java/vimification/logic/LogicManager.java
  src/main/java/vimification/logic/parser/VimificationParser.java
  src/main/java/vimification/model/task/Status.java
  src/main/java/vimification/model/task/components/DateTime.java
  src/main/java/vimification/model/task/components/Description.java
  src/main/java/vimification/model/util/SampleDataUtil.java
  src/main/java/vimification/taskui/CommandInput.java
  src/main/java/vimification/taskui/MainScreen.java
  src/main/java/vimification/taskui/TaskCard.java
  src/main/java/vimification/taskui/TaskDetailPanel.java
  src/main/java/vimification/taskui/UiPart.java
  src/main/java/vimification/ui/CommandBox
  src/main/java/vimification/ui/HelpWindow
  src/main/java/vimification/ui/MainWindow
  src/main/java/vimification/ui/PersonCard
  src/main/java/vimification/ui/PersonListPanel
  src/main/java/vimification/ui/ResultDisplay
  src/main/java/vimification/ui/StatusBarFooter
  src/main/java/vimification/ui/Ui.java
  src/main/java/vimification/ui/UiManager
  src/main/java/vimification/ui/UiPart
Labels: gui

#65 DevGuide: add sections about parser
  docs/DeveloperGuide.md
Labels: documentation

#55 More unit tests for parser
  src/main/java/vimification/logic/parser/ApplicativeParser.java
  src/main/java/vimification/logic/parser/VimificationParser.java
  src/test/java/vimification/logic/parser/ApplicativeParserTest.java
  src/test/java/vimification/logic/parser/VimificationParserTest.java
Labels: cli

#60 Implement SearchByKeywordCommand
  src/main/java/vimification/Gui.java
  src/main/java/vimification/internal/Logic.java
  src/main/java/vimification/internal/LogicManager.java
  src/main/java/vimification/internal/command/Command.java
  src/main/java/vimification/internal/command/CommandException.java
  src/main/java/vimification/internal/command/CommandResult.java
  src/main/java/vimification/internal/command/logic/CreateCommand.java
  src/main/java/vimification/internal/command/logic/DeleteCommand.java
  src/main/java/vimification/internal/command/logic/LogicCommand.java
  src/main/java/vimification/internal/command/logic/UndoableLogicCommand.java
  src/main/java/vimification/internal/command/oldcode/ClearCommand
  src/main/java/vimification/internal/command/oldcode/EditCommand
  src/main/java/vimification/internal/command/oldcode/ExitCommand
  src/main/java/vimification/internal/command/oldcode/FindCommand
  src/main/java/vimification/internal/command/oldcode/HelpCommand
  src/main/java/vimification/internal/command/oldcode/ListCommand
  src/main/java/vimification/internal/command/view/SearchByKeywordCommand.java
  src/main/java/vimification/internal/command/view/SearchCommand.java
  src/main/java/vimification/internal/command/view/ViewCommand.java
  src/main/java/vimification/internal/parser/AddCommandParser
  src/main/java/vimification/internal/parser/AddressBookParser
  src/main/java/vimification/internal/parser/ApplicativeParser.java
  src/main/java/vimification/internal/parser/ArgumentMultimap.java
  src/main/java/vimification/internal/parser/ArgumentTokenizer.java
  src/main/java/vimification/internal/parser/CharPredicate.java
  src/main/java/vimification/internal/parser/CliSyntax.java
  src/main/java/vimification/internal/parser/CreateCommandParser.java
  src/main/java/vimification/internal/parser/DeleteCommandParser.java
  src/main/java/vimification/internal/parser/EditCommandParser
  src/main/java/vimification/internal/parser/FindCommandParser
  src/main/java/vimification/internal/parser/LogicCommandParser.java
  src/main/java/vimification/internal/parser/Pair.java
  src/main/java/vimification/internal/parser/ParserException.java
  src/main/java/vimification/internal/parser/ParserUtil
  src/main/java/vimification/internal/parser/Prefix.java
  src/main/java/vimification/internal/parser/StringView.java
  src/main/java/vimification/internal/parser/VimificationParser.java
  src/main/java/vimification/model/DisplayTaskList.java
  src/main/java/vimification/model/LogicTaskList.java
  src/main/java/vimification/model/task/Task.java
  src/main/java/vimification/model/task/TaskDescriptionContainsKeywordsPredicate.java
  src/main/java/vimification/taskui/CommandInput.java
  src/main/java/vimification/taskui/MainScreen.java
  src/main/java/vimification/taskui/UiManager.java
  src/test/java/vimification/logic/parser/ApplicativeParserTest.java
  src/test/java/vimification/logic/parser/CreateCommandParserTest.java
  src/test/java/vimification/logic/parser/VimificationParserTest.java
Labels: enhancement, cli

#75 Update UI portion of DeveloperGuide
  docs/DeveloperGuide.md
  docs/images/UiClassDiagram.png
Labels: documentation

#80 Fix User stories formatting
  docs/DeveloperGuide.md
Labels: documentation

#81 Add more information for Developer Guide
  docs/DeveloperGuide.md
Labels: documentation

#83 Update UG
  docs/UserGuide.md
Labels: documentation

#70 Implement Task tagging feature
  src/main/java/vimification/internal/command/logic/AddTagCommand.java
  src/main/java/vimification/internal/command/logic/RemoveTagCommand.java
  src/main/java/vimification/model/LogicTaskList.java
  src/main/java/vimification/model/task/Task.java
Labels: enhancement

#121 SearchCommand: allow OR search
  src/main/java/vimification/internal/command/view/AndComposedSearchCommand.java
  src/main/java/vimification/internal/command/view/OrComposedSearchCommand.java
  src/main/java/vimification/internal/parser/CommandParserUtil.java
  src/main/java/vimification/internal/parser/SearchCommandParser.java
Labels: enhancement
